### ISSUE TITLE
Question: how to build the separator stl

### ISSUE THREAD

**Issue by magcode** [2dom/PixelTimes#15]
Hi,

I want to make a slightly changed version of your [3mm separator grid](https://www.thingiverse.com/thing:2892122) for use with a 64x32 display.
Can you give me an hint how you created the STL? (I'm a 3D beginner)
As it is a rather easy 3D model I was thinking that maybe you created it programmatically (e.g. using [numpy-stl](https://github.com/WoLpH/numpy-stl).

Thanks!

**Comment by magcode** [comment]
After some reading I assume you build it using scad...!? Would you mind sharing the sources?

Thanks

**Comment by scallc** [comment]
Did a grille for the 64x32 on [Thingiverse](https://www.thingiverse.com/scallopc/designs) if this helps.

**Comment by magcode** [comment]
Thanks @scallc !
Had a look at your model, looks good!

meanwhile I played around with scad and was able to build a model myself:

```
//Module size 192mmX96mm with 3mm LED pitch
meshSolid=0.42;
meshSpace=2.58;
height=96 + meshSolid;
width=192 + meshSolid;
thickness=3;

    color("red")
    for (i=[0:64]) {
        translate([0,i*(meshSolid+meshSpace),-thickness/2]) {
          cube([height,meshSolid,thickness]);
        }
    }
    color("blue")
    for (i=[0:32]) {
        translate([i*(meshSolid+meshSpace),0,-thickness/2]) {
          cube([meshSolid,width,thickness]);
        }
    }
```

May I ask questions?

The thickness of your "walls" seem to be 0.8mm. Does this fit well?
Did your 3D printing give you that accurate 0.8mm thickness?

**Comment by scallc** [comment]
Hi @magcode , 

I don't have a vernier caliper with me but I think it's around that thickness. Depends on your print settings too! (e.g. layer height).

Cheers

**Comment by magcode** [comment]
Ok. Thanks!
